version: '2'
volumes:
  nginx: {}

services:
  dnsmasq:
    image: andyshinn/dnsmasq
    ports:
      - '15353:53/udp'
      - '15353:53/tcp'
    container_name: dnsmasq
    # volumes:
    #   - /private/etc/resolv.conf:/etc/host_resolv.conf:ro
    restart: always
    cap_add:
      - NET_ADMIN
    command:
      - --log-queries
      - --no-hosts
      # - --resolv-file=/etc/host_resolv.conf
      - --no-resolv
      - --clear-on-reload
      - --domain-needed
      - --log-facility=-
      - --address=/dev/127.0.0.1
      - --address=/local.goodguide.com/127.0.0.1
      - --server=8.8.8.8
      # - '--server=/*.apple.com/#'
      # - --bogus-nxdomain=198.105.254.104 # t-mobile DNS not-found search page
      # - --bogus-nxdomain=198.105.244.104 # t-mobile DNS not-found search page
      # - --bogus-nxdomain=92.242.132.15 # BT DNS not-found search page

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./etc/nginx:/etc/nginx/
    command:
      - nginx
      - -g
      - 'daemon off; error_log /var/log/nginx/error.log info;'
    restart: always
    network_mode: bridge
    tmpfs:
      - /data/nginx/cache

  dockergen:
    image: jwilder/docker-gen
    container_name: dockergen
    command:
      - -notify-output
      - -notify-sighup
      - nginx
      - -watch
      - /etc/docker-gen/templates/nginx.tmpl
      - /etc/nginx/conf.d/default.conf
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
      - ./etc/nginx:/etc/nginx/
    restart: always
    network_mode: bridge

  # autodock:
  #   image: prologic/autodock
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro

  # autodock-logger:
  #   image: prologic/autodock-logger
  #   links:
  #     - autodock

  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    container_name: cadvisor
    restart: always
    network_mode: bridge
    environment:
      VIRTUAL_HOST: cadvisor.local.dev
